version: "3"

services:
  miniconda3:
    image: aaamlp
    container_name: aaamlp
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8888:8888
    volumes:
      - .:/opt/study/aaamlp_transcription
